### ISSUE TITLE
请问怎么启用带有注意力机制的SSD呢

### ISSUE THREAD

**Issue by Songhuanhui** [Robust-Jay/SSD-Resnet-Attention-FeatureFusion#1]
请问怎么启用带有注意力机制的SSD呢

**Comment by withoutyourself** [comment]
我已经重构resnet backbone代码，你可以进入configs/resnet50_ssd300_voc0712.yaml 可以看到RESNET部分：
RESNET:
    SE: False
    CBAM: False
    FUSION: False
    BLOCKS: [3, 4, 6, 3]
    EXTRAS: [512, 256, 64, 64]
将SE或者CBAM设置为True即可
注意：只用设置其中之一，因为二者其实本质差不多

**Comment by Songhuanhui** [comment]
您好，非常高兴收到您的答疑和回复
我看到您上传的代码resnet_input_300.py中有：if replace_stride_with_dilation is none:
 
&nbsp;&nbsp; replace_stride_with_dilation = [false,false,false]

请问如果我想使用dilated Convolution 该如何修改呢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "withoutyourself/SSD-Resnet-Attention-FeatureFusion"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月2日(星期天) 下午3:21
收件人:&nbsp;"withoutyourself/SSD-Resnet-Attention-FeatureFusion"<SSD-Resnet-Attention-FeatureFusion@noreply.github.com&gt;;
抄送:&nbsp;"1624880406"<1624880406@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [withoutyourself/SSD-Resnet-Attention-FeatureFusion] 请问怎么启用带有注意力机制的SSD呢 (#1)





 
我已经重构resnet backbone代码，你可以进入configs/resnet50_ssd300_voc0712.yaml 可以看到RESNET部分：
 RESNET:
 SE: False
 CBAM: False
 FUSION: False
 BLOCKS: [3, 4, 6, 3]
 EXTRAS: [512, 256, 64, 64]
 将SE或者CBAM设置为True即可
 注意：只用设置其中之一，因为二者其实本质差不多

**Comment by Songhuanhui** [comment]
> 我已经重构resnet backbone代码，你可以进入configs/resnet50_ssd300_voc0712.yaml 可以看到RESNET部分：
> RESNET:
> SE: False
> CBAM: False
> FUSION: False
> BLOCKS: [3, 4, 6, 3]
> EXTRAS: [512, 256, 64, 64]
> 将SE或者CBAM设置为True即可
> 注意：只用设置其中之一，因为二者其实本质差不多

您好，非常高兴收到您的答疑和回复
我看到您上传的代码resnet_input_300.py中有：if replace_stride_with_dilation is none:

&nbsp;&nbsp; replace_stride_with_dilation = [false,false,false]

请问如果我想使用dilated Convolution 该如何修改呢
